2020-12-22 17:04:37,959 ui_test INFO basepage.py [第83行] 当前动作为：输入用户名
2020-12-22 17:04:37,959 ui_test INFO basepage.py [第26行] 等待 ('xpath', '//input[@name="account"]') 元素的出现。
2020-12-22 17:04:37,975 ui_test INFO basepage.py [第37行] 查找 ('xpath', '//input[@name="account"]') 元素。
2020-12-22 17:04:37,978 ui_test INFO basepage.py [第86行] 需要输入的元素是:<selenium.webdriver.remote.webelement.WebElement (session="5143100e19305ecb30342a317efbe233", element="2885447e-de73-4f53-9c80-d21c08199d6f")>。
2020-12-22 17:04:38,033 ui_test INFO basepage.py [第83行] 当前动作为：输入密码
2020-12-22 17:04:38,034 ui_test INFO basepage.py [第26行] 等待 ('xpath', '//input[@name="pass"]') 元素的出现。
2020-12-22 17:04:38,051 ui_test INFO basepage.py [第37行] 查找 ('xpath', '//input[@name="pass"]') 元素。
2020-12-22 17:04:38,055 ui_test INFO basepage.py [第86行] 需要输入的元素是:<selenium.webdriver.remote.webelement.WebElement (session="5143100e19305ecb30342a317efbe233", element="65a37b82-9070-4145-b9f2-0a391626167f")>。
2020-12-22 17:04:38,097 ui_test INFO basepage.py [第70行] 当前动作为：点击登录
2020-12-22 17:04:38,097 ui_test INFO basepage.py [第26行] 等待 ('xpath', '//div[contains(@class,"pt-login")]//a[text()="登录"]') 元素的出现。
2020-12-22 17:04:38,109 ui_test INFO basepage.py [第37行] 查找 ('xpath', '//div[contains(@class,"pt-login")]//a[text()="登录"]') 元素。
2020-12-22 17:04:38,114 ui_test INFO basepage.py [第73行] 需要点击的元素是:<selenium.webdriver.remote.webelement.WebElement (session="5143100e19305ecb30342a317efbe233", element="85e78a43-b051-4309-841a-3b7557690eb1")>。
2020-12-22 17:04:38,145 ui_test INFO basepage.py [第70行] 当前动作为：根据班级名字进入班级
2020-12-22 17:04:38,145 ui_test INFO basepage.py [第26行] 等待 ('xpath', '//a[text()="Meghan Brooks"]') 元素的出现。
2020-12-22 17:04:39,350 ui_test INFO basepage.py [第37行] 查找 ('xpath', '//a[text()="Meghan Brooks"]') 元素。
2020-12-22 17:04:39,354 ui_test INFO basepage.py [第73行] 需要点击的元素是:<selenium.webdriver.remote.webelement.WebElement (session="5143100e19305ecb30342a317efbe233", element="0195c449-bfb6-4657-bc42-4faa2ad789c3")>。
2020-12-22 17:04:39,554 ui_test INFO basepage.py [第70行] 当前动作为：首页—点击考勤
2020-12-22 17:04:39,554 ui_test INFO basepage.py [第26行] 等待 ('xpath', '//span[text()="考勤"]/parent::a') 元素的出现。
2020-12-22 17:04:39,555 ui_test ERROR basepage.py [第31行] 元素等待失败。
Traceback (most recent call last):
  File "E:\PO模型练习\common\basepage.py", line 29, in wait_ele_visible
    wait.until(EC.visibility_of_element_located(loc))
  File "D:\python\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "D:\python\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "D:\python\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "D:\python\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=87.0.4280.66)

2020-12-22 17:04:39,559 ui_test INFO basepage.py [第107行] 开始截图，图片路径在 E:\PO模型练习\outputs\screenshots\首页—点击考勤_2020-12-22 17：04：39.png。
2020-12-22 17:04:39,560 ui_test ERROR basepage.py [第111行] 图片截取失败！！
Traceback (most recent call last):
  File "E:\PO模型练习\common\basepage.py", line 29, in wait_ele_visible
    wait.until(EC.visibility_of_element_located(loc))
  File "D:\python\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "D:\python\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "D:\python\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "D:\python\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=87.0.4280.66)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\PO模型练习\common\basepage.py", line 109, in __screenshot
    self.driver.save_screenshot(scr_path)
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=87.0.4280.66)

